#!/usr/bin/env bash

# Print an error message and exit.
panic()
{
	echo "ERROR: $@"
	exit 1
}

# Get the directory in which the currently running script is located.
cmd_dir=$(dirname "$0") || panic "cannot determine command directory"

interpreter="$cmd_dir/lisp"

echo "Running examples/fib.lsp."
echo "> This program prints out the first 7 fibonacci numbers in sequence."
$interpreter "$cmd_dir/examples/fib.lsp"

echo "Running examples/problem1.lsp"
echo "> This program solves question 1 from Project Euler."
echo "> The answer is the sum of all numbers less than 1000"
echo "> which are a multiple of either 5 or 3."
$interpreter "$cmd_dir/examples/problem1.lsp"